data:
  points_dir: "data/points"
  output_dir: "result/solve_point/fista"
  batch_pattern: "points_batch_*.pt"
  threshold_A: 0.0001
  threshold_b: 0.8

solver:
  type: "fista" # Options: fista, ista
  lambda_reg: 0.0
  n_iter: 800
  positivity: true
  lipchitz: 20.0 # Optional, default 1.0 if not specified
  batch_size: 30000 # Sub-batch size for solving on GPU

device: "cuda" # or cpu

# Optional: export mesh after reconstruction.
# If omitted, no mesh is exported.
mesh_iso: [0.75, 1.0, 2.0]
