data:
  points_dir: "data/points/20um_imgs/ds0p5_30000"
  output_dir: "result/solve_point/newton/20um_imgs/ds0p5_30000"
  batch_pattern: "points_batch_*.pt"
  threshold_A: 0.05
  threshold_b: 0.01

solver:
  type: "newton" # Options: newton, ista
  lambda_reg: 0.00001
  n_iter: 100
  positivity: true
  batch_size: 500 # Sub-batch size for solving on GPU

device: "cuda" # or cpu

# Optional: export mesh after reconstruction.
# If omitted, no mesh is exported.
mesh_iso: [0.75, 1.0, 2.0]
