data:
  points_dir: "data/points"
  output_dir: "result/point_solve/ista"
  batch_pattern: "points_batch_*.pt"
  threshold_A: 0.20
  threshold_b: 1.0

solver:
  type: "ista" # Options: fista, ista
  lambda_reg: 0.0
  n_iter: 100
  positivity: true
  batch_size: 1000 # Sub-batch size for solving on GPU

device: "cuda" # or cpu
